version: '3.8'

services:
  user-service:
    image: nyura-user-service:0.0.1
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB: userdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
      ACCESS_TOKEN_SECRET: "b858HK56DUuxGraUtFSj4KA/ysWxcenqZ3M1hovR8p2zjCXzOyYgn6V++2JT1Ph3"
      REFRESH_TOKEN_SECRET: "gLGxGagS0+rgInro0oW3gs2JBdYl0AT108qRfAW4PYnPSF7KSgWS04LME3/GhTIe"
